version: "3.8"

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@c0^JiGrg5Nj^YFu0B8wt0x7*evxzC^nyxOa"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: ["start-dev"]

volumes:
  sql_data:
