IF EXISTS (SELECT * FROM sys.databases WHERE name = 'NextStop')
BEGIN
    ALTER DATABASE NextStop SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE NextStop;
END;
GO

IF EXISTS (SELECT * FROM sys.databases WHERE name = 'testNextStop')
BEGIN
    ALTER DATABASE testNextStop SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE testNextStop;
END;
GO

CREATE DATABASE NextStop;
GO

CREATE DATABASE testNextStop;
GO

USE NextStop;
GO

CREATE TABLE PERSON (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    DATEOFBIRTH DATE,
    EMAIL VARCHAR(255) UNIQUE
);

CREATE TABLE ROUTE (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTENUMBER VARCHAR(20),
    VALIDFROM DATE,
    VALIDTO DATE,
    ISWEEKEND BIT
);

CREATE TABLE STOP (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    NAME VARCHAR(100),
    SHORTCODE VARCHAR(10) UNIQUE,
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8)
);

CREATE TABLE ROUTE_STOP (
    ROUTEID INT,
    STOPID INT,
    STOPORDER INT,
    PRIMARY KEY (ROUTEID, STOPID),
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STOPID) REFERENCES STOP(ID) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTEID INT,
    STOPID INT,
    SCHEDULEDTIME TIME,
    ISHOLIDAY BIT,
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STOPID) REFERENCES STOP(ID) ON DELETE CASCADE
);

CREATE TABLE HOLIDAY (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    DATE DATE,
    NAME VARCHAR(50),
    ISSCHOOLHOLIDAY BIT
);

CREATE TABLE CHECKIN (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTEID INT NOT NULL,
    STOPID INT NOT NULL,
    CHECKINTIME DATETIME NOT NULL,
    DELAYINMINUTES INT,
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STOPID) REFERENCES STOP(ID) ON DELETE CASCADE
);

CREATE TABLE CLIENT (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    CLIENTNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORDHASH VARCHAR(256) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE API_KEY (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    CLIENTID INT NOT NULL,
    KEYVALUE UNIQUEIDENTIFIER DEFAULT NEWID(),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CLIENTID) REFERENCES CLIENT(ID) ON DELETE CASCADE
);

CREATE TABLE STATISTIC (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTEID INT,
    REPORTDATE DATE NOT NULL,
    AVERAGEDELAY INT,
    ONTIME_PERCENTAGE DECIMAL(5, 2),
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE
);
GO


USE testNextStop;
GO

CREATE TABLE PERSON (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    DATEOFBIRTH DATE,
    EMAIL VARCHAR(255) UNIQUE
);

CREATE TABLE ROUTE (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTENUMBER VARCHAR(20),
    VALIDFROM DATE,
    VALIDTO DATE,
    ISWEEKEND BIT
);

CREATE TABLE STOP (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    NAME VARCHAR(100),
    SHORTCODE VARCHAR(10) UNIQUE,
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8)
);

CREATE TABLE ROUTE_STOP (
    ROUTEID INT,
    STOPID INT,
    STOPORDER INT,
    PRIMARY KEY (ROUTEID, STOPID),
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STOPID) REFERENCES STOP(ID) ON DELETE CASCADE
);

CREATE TABLE SCHEDULE (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTEID INT,
    STOPID INT,
    SCHEDULEDTIME TIME,
    ISHOLIDAY BIT,
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STOPID) REFERENCES STOP(ID) ON DELETE CASCADE
);

CREATE TABLE HOLIDAY (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    DATE DATE,
    NAME VARCHAR(50),
    ISSCHOOLHOLIDAY BIT
);

CREATE TABLE CHECKIN (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTEID INT NOT NULL,
    STOPID INT NOT NULL,
    CHECKINTIME DATETIME NOT NULL,
    DELAYINMINUTES INT,
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (STOPID) REFERENCES STOP(ID) ON DELETE CASCADE
);

CREATE TABLE CLIENT (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    CLIENTNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORDHASH VARCHAR(256) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
);

CREATE TABLE API_KEY (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    CLIENTID INT NOT NULL,
    KEYVALUE UNIQUEIDENTIFIER DEFAULT NEWID(),
    CREATED_AT DATETIME DEFAULT GETDATE(),
    FOREIGN KEY (CLIENTID) REFERENCES CLIENT(ID) ON DELETE CASCADE
);

CREATE TABLE STATISTIC (
    ID INT PRIMARY KEY IDENTITY(1, 1),
    ROUTEID INT,
    REPORTDATE DATE NOT NULL,
    AVERAGEDELAY INT,
    ONTIME_PERCENTAGE DECIMAL(5, 2),
    FOREIGN KEY (ROUTEID) REFERENCES ROUTE(ID) ON DELETE CASCADE
);
GO
