name: .NET Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore NextStop/NextStop.sln

      - name: Build the solution
        run: dotnet build NextStop/NextStop.sln --no-restore --configuration Release
